version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DATABASE_URL=postgresql://postgres:newsinjapan1234@db.ltcxrwkbmxdklbemcipf.supabase.co:5432/postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    networks:
      - app-net
    restart: always

networks:
  app-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.238.0/24
        - subnet: 2001:db8:1::/64

volumes:
  db-data:
