version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:newsinjapan1234@db.ltcxrwkbmxdklbemcipf.supabase.co:5432/postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    restart: always


volumes:
  db-data:
